IT-Asset Custody/Controllers/RoleController.cs
using IT_Asset_Custody.DAL;
using IT_Asset_Custody.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace IT_Asset_Custody.Controllers
{
    public class RoleController : Controller
    {

        ApplicationDbContext context = new ApplicationDbContext();
        // GET: Role
        public ActionResult Index()
        {

            if (User.Identity.IsAuthenticated)
            {


                if (!isAdminUser())
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

            var Roles = context.Roles.ToList();
            return View(Roles);

        }
        public Boolean isAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var s = UserManager.GetRoles(user.GetUserId());
                if (s[0].ToString() == "Admin")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            return false;
        }
    }
}

IT-Asset Custody/Views/usercontroller/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.DisplayMenu="Yes")
{
    <h1>Welcome Admin, You Can Create User Roles.</h1>
    <h3>
        <li>@Html.ActionLink("Manage Role","Index","Role")</li>
    </h3>
}
else
{
    <h2>Welcome<strong>@ViewBag.Name</strong> :) .We will Add user module soon </h2>
}